extern const GeoLayout wmotr_area_1_geo[];
extern const GeoLayout wmotr_area_1[];
extern const Collision wmotr_area_1_collision[];
extern const MacroObject wmotr_area_1_macro_objs[];
extern const GeoLayout wmotr_area_2_geo[];
extern const GeoLayout wmotr_area_2[];
extern const Collision wmotr_area_2_collision[];
extern const MacroObject wmotr_area_2_macro_objs[];
extern Lights1 wmotr_dl_tempwalsl_lights;
extern Lights1 wmotr_dl_banner_lights;
extern Lights1 wmotr_dl_accentcolor_lights;
extern Lights1 wmotr_dl_black_lights;
extern Lights1 wmotr_dl_gamescreen_lights;
extern Lights1 wmotr_dl_basecolor_lights;
extern Lights1 wmotr_dl_frontcolor_lights;
extern u8 wmotr_dl_brick2_16color_ci4[];
extern u8 wmotr_dl_brick2_16color_ci4_pal_rgba16[];
extern u8 wmotr_dl_silo_climb_transp_banner_ci4[];
extern u8 wmotr_dl_silo_climb_transp_banner_ci4_pal_rgba16[];
extern u8 wmotr_dl_silo_climb_transp_ci4[];
extern u8 wmotr_dl_silo_climb_transp_ci4_pal_rgba16[];
extern u8 wmotr_dl_silo_climb_ci4[];
extern u8 wmotr_dl_silo_climb_ci4_pal_rgba16[];
extern u8 wmotr_dl_darkwood_16coloridea64x64_i8[];
extern u8 wmotr_dl_brick2_16color_i8[];
extern Vtx wmotr_dl_arcadeRoom_mesh_layer_1_vtx_cull[8];
extern Vtx wmotr_dl_arcadeRoom_mesh_layer_1_vtx_0[192];
extern Gfx wmotr_dl_arcadeRoom_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_6_vtx_cull[8];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_6_vtx_0[6];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_6_tri_0[];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_6_vtx_1[16];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_6_tri_1[];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_1_vtx_cull[8];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_1_vtx_0[48];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_1_vtx_1[20];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_1_tri_1[];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_1_vtx_2[16];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_1_tri_2[];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_1_vtx_3[38];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_1_tri_3[];
extern Vtx wmotr_dl_base_cabinet_mesh_layer_1_vtx_4[20];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_1_tri_4[];
extern Vtx wmotr_dl_a2walls_mesh_layer_1_vtx_cull[8];
extern Vtx wmotr_dl_a2walls_mesh_layer_1_vtx_0[87];
extern Gfx wmotr_dl_a2walls_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_instant_warps_mesh_layer_1_vtx_cull[8];
extern Vtx wmotr_dl_instant_warps_mesh_layer_1_vtx_0[3];
extern Gfx wmotr_dl_instant_warps_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_instant_warps_mesh_layer_1_vtx_1[3];
extern Gfx wmotr_dl_instant_warps_mesh_layer_1_tri_1[];
extern Vtx wmotr_dl_main_silo_mesh_layer_1_vtx_cull[8];
extern Vtx wmotr_dl_main_silo_mesh_layer_1_vtx_0[400];
extern Gfx wmotr_dl_main_silo_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_main_silo_mesh_layer_1_vtx_1[36];
extern Gfx wmotr_dl_main_silo_mesh_layer_1_tri_1[];
extern Vtx wmotr_dl_main_silo_mesh_layer_1_vtx_2[21];
extern Gfx wmotr_dl_main_silo_mesh_layer_1_tri_2[];
extern Vtx wmotr_dl_main_silo_mesh_layer_1_vtx_3[122];
extern Gfx wmotr_dl_main_silo_mesh_layer_1_tri_3[];
extern Gfx mat_wmotr_dl_tempwalsl[];
extern Gfx mat_revert_wmotr_dl_tempwalsl[];
extern Gfx mat_wmotr_dl_banner[];
extern Gfx mat_revert_wmotr_dl_banner[];
extern Gfx mat_wmotr_dl_fullsize[];
extern Gfx mat_revert_wmotr_dl_fullsize[];
extern Gfx mat_wmotr_dl_accentcolor[];
extern Gfx mat_wmotr_dl_black[];
extern Gfx mat_wmotr_dl_gamescreen[];
extern Gfx mat_revert_wmotr_dl_gamescreen[];
extern Gfx mat_wmotr_dl_basecolor[];
extern Gfx mat_wmotr_dl_frontcolor[];
extern Gfx mat_wmotr_dl_wood_001_layer1[];
extern Gfx mat_revert_wmotr_dl_wood_001_layer1[];
extern Gfx mat_wmotr_dl_down_instant_warp_layer1[];
extern Gfx mat_revert_wmotr_dl_down_instant_warp_layer1[];
extern Gfx mat_wmotr_dl_up_instant_warp_002_layer1[];
extern Gfx mat_revert_wmotr_dl_up_instant_warp_002_layer1[];
extern Gfx mat_wmotr_dl_brick_layer1[];
extern Gfx mat_revert_wmotr_dl_brick_layer1[];
extern Gfx wmotr_dl_arcadeRoom_mesh_layer_1[];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_6[];
extern Gfx wmotr_dl_base_cabinet_mesh_layer_1[];
extern Gfx wmotr_dl_a2walls_mesh_layer_1[];
extern Gfx wmotr_dl_instant_warps_mesh_layer_1[];
extern Gfx wmotr_dl_main_silo_mesh_layer_1[];
extern Gfx wmotr_dl_material_revert_render_settings[];
